services:
  kaggle-runner:
    build: .
    container_name: kaggle-runner
    restart: unless-stopped
    environment:
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}
    expose:
      - "8000"
    networks:
      - n8n-net

networks:
  n8n-net:
    name: invents-n8n-gxu2qx
    external: true
